ads/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name = 'ads'

urlpatterns = [
    # ex: /hello/

    path('', views.AdListView.as_view(), name='all'),

    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),

    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),

    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),

    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

cats/urls.py
from django.urls import path

from . import views

app_name = 'cats'

urlpatterns = [

    path('', views.MainView.as_view(), name='all'),

    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),

    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),

]

pets/urls.py
from django.urls import path

from . import views

app_name = 'pets'

urlpatterns = [

    path('', views.MainView.as_view(), name='all'),

    path('main/create/', views.PetCreate.as_view(), name='pet_create'),
    path('main/<int:pk>/update/', views.PetUpdate.as_view(), name='pet_update'),
    path('main/<int:pk>/delete/', views.PetDelete.as_view(), name='pet_delete'),

    path('lookup/', views.TypeView.as_view(), name='type_list'),
    path('lookup/create/', views.TypeCreate.as_view(), name='type_create'),
    path('lookup/<int:pk>/update/', views.TypeUpdate.as_view(), name='type_update'),
    path('lookup/<int:pk>/delete/', views.TypeDelete.as_view(), name='type_delete'),

]

pets/models.py
from django.db import models
from django.core.validators import MinLengthValidator

class Type(models.Model):
    name = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Type must be greater than 1 character")]
    )

    def __str__(self):
        return self.name

class Pet(models.Model):
    nickname = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    age = models.PositiveIntegerField()
    cost = models.PositiveIntegerField()
    comments = models.CharField(max_length=300)
    type = models.ForeignKey('Type', on_delete=models.CASCADE, null=False)

    def __str__(self):
        return self.nickname

pets/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from pets.models import Pet, Type
#from autos.forms import MakeForm

# Create your views here.


class MainView(LoginRequiredMixin, View):
    def get(self, request):
        tc = Type.objects.all().count()
        pl = Pet.objects.all()

        ctx = {'type_count': tc, 'pet_list': pl}
        return render(request, 'pets/pet_list.html', ctx)


class TypeView(LoginRequiredMixin, View):
    def get(self, request):
        tl = Type.objects.all()
        ctx = {'type_list': tl}
        return render(request, 'pets/type_list.html', ctx)


class TypeCreate(LoginRequiredMixin, CreateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')

class TypeUpdate(LoginRequiredMixin, UpdateView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class TypeDelete(LoginRequiredMixin, DeleteView):
    model = Type
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


# Take the easy way out on the main table
# These views do not need a form because CreateView, etc.
# Build a form object dynamically based on the fields
# value in the constructor attributes
class PetCreate(LoginRequiredMixin, CreateView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class PetUpdate(LoginRequiredMixin, UpdateView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')


class PetDelete(LoginRequiredMixin, DeleteView):
    model = Pet
    fields = '__all__'
    success_url = reverse_lazy('pets:all')

# We use reverse_lazy rather than reverse in the class attributes
# because views.py is loaded by urls.py and in urls.py as_view() causes
# the constructor for the view class to run before urls.py has been
# completely loaded and urlpatterns has been processed.

# References

# https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-editing/#createview

pets/templates/pets/pet_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Pet</h1>

<p>Are you sure you want to delete the pet: {{ pet }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

pets/templates/pets/pet_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'pets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

pets/templates/pets/pet_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Pet List</h1>
  {% if pet_list %}
  <ul>
    {% for pet in pet_list %}
      <li>
          {{ pet.nickname }} ({{ cat.type }})
          (<a href="{% url 'pets:pet_update' pet.id %}">Update</a> |
          <a href="{% url 'pets:pet_delete' pet.id %}">Delete</a>) <br/>
          Will come home with you for: ${{ pet.cost }} and is: {{ pet.age }} year(s) old.
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no pets in the store.</p>
  {% endif %}
  <p>
    {% if type_count > 0 %}
      <a href="{% url 'pets:pet_create' %}">Add a pet</a>
    {% else %}
      Please add a pet type before you add a pet.
    {% endif %}
  </p>
  <p>
  <a href="{% url 'pets:type_list' %}">View types</a> ({{ type_count }}) |
    <a href="{% url 'pets:type_create' %}">Add a type</a>
    <!-- I wanted to add some flare and change just the html a bit but the autograder asks for specific things :(-->
  </p>
{% endblock %}

pets/templates/pets/type_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Pet Type</h1>

<p>Are you sure you want to delete the type: {{ type }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

pets/templates/pets/type_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'pets:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

pets/templates/pets/type_list.html
{% extends "base_bootstrap.html" %}

{% block content %}
  <h1>Pet Type List</h1>
  {% if type_list %}
  <ul>
    {% for type in type_list %}
      <li>
          {{ type.name }}
         (<a href="{% url 'pets:type_update' type.id %}">Update</a> |
          <a href="{% url 'pets:type_delete' type.id %}">Delete</a>)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no pet Types in the library.</p>
  {% endif %}
  <p><a href="{% url 'pets:type_create' %}">Add a type</a></p>
  <p>
    <a href="{% url 'pets:all' %}">Back to pets</a>
  </p>
{% endblock %}