ads/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name = 'ads'

urlpatterns = [
    # ex: /hello/

    path('', views.AdListView.as_view(), name='all'),

    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),

    path('ad/create',
        views.AdCreateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_create'),

    path('ad/<int:pk>/update',
        views.AdUpdateView.as_view(success_url=reverse_lazy('ads:all')), name='ad_update'),

    path('ad/<int:pk>/delete',
        views.AdDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_delete'),

    path('ad_picture/<int:pk>', views.stream_file, name='ad_picture'),

    path('ad/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='ad_comment_create'),

    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('ads:all')), name='ad_comment_delete'),

    path('ad/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='ad_favorite'),

    path('ad/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='ad_unfavorite'),
]

gifts/urls.py
from django.urls import path, reverse_lazy
from . import views
from django.views.generic import TemplateView

app_name = 'gifts'

urlpatterns = [
    # ex: /hello/
    path('signup', views.signup, name='signup'),

    path('', views.MemberListView.as_view(), name='all'),

    path('gift/<int:pk>', views.GiftDetailView.as_view(), name='gift_detail'),

    path('gift/create',
        views.GiftCreateView.as_view(success_url=reverse_lazy('gifts:all')), name='gift_create'),

    path('gift/gift_link_create',
        views.GiftCreateFromLinkView.as_view(success_url=reverse_lazy('gifts:all')), name='gift_link_create'),

    path('gift/<int:pk>/update',
        views.GiftUpdateView.as_view(success_url=reverse_lazy('gifts:all')), name='gift_update'),

    path('gift/<int:pk>/delete',
        views.GiftDeleteView.as_view(success_url=reverse_lazy('gifts:all')), name='gift_delete'),

    path('gift_picture/<int:pk>', views.stream_file, name='gift_picture'),

    path('gift/<int:pk>/comment',
        views.CommentCreateView.as_view(), name='gift_comment_create'),

    path('comment/<int:pk>/delete',
        views.CommentDeleteView.as_view(success_url=reverse_lazy('gifts:all')), name='gift_comment_delete'),

    path('gift/<int:pk>/favorite',
        views.AddFavoriteView.as_view(), name='gift_favorite'),

    path('gift/<int:pk>/unfavorite',
        views.DeleteFavoriteView.as_view(), name='gift_unfavorite'),

    path('user/<int:pk>', views.MemberGiftListView.as_view(), name ='member_gift_list'),
    path('users/', views.MemberListView.as_view(), name ='member_list'),

     path('jsondata',views.ReportJsonData,name = "jsondata"),

]

gifts/forms.py
from django import forms
from gifts.models import Gift
from django.core.files.uploadedfile import InMemoryUploadedFile
from gifts.humanize import naturalsize

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class SignUpForm(UserCreationForm):
    name = forms.CharField(max_length=30, required=False, help_text='Required.')
    birth_date = forms.DateField(help_text='Required. Format: YYYY-MM-DD')
    class Meta:
        model = User
        fields = ('username', 'name' , 'birth_date', 'password1', 'password2', )

# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    class Meta:
        model = Gift
        fields = ['title', 'price', 'text', 'picture','tags', 'link']  # Picture is manual

    def __init__(self, *args, **kwargs):
        super(CreateForm, self).__init__(*args, **kwargs)
        self.fields['link'].required = False


    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")

    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()    # Add this

        return instance

class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)
# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

gifts/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse, JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile

from gifts.models import Gift, Member
from ads.models import Comment, Fav
from gifts.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from gifts.forms import CreateForm, CommentForm, SignUpForm
from gifts.utils import dump_queries, get_link_info
from bs4 import BeautifulSoup
import requests
import base64


from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

from django.db.models import Q
from django.contrib.humanize.templatetags.humanize import naturaltime

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.member.birth_date = form.cleaned_data.get('birth_date')
            user.member.name = form.cleaned_data.get('name')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('/')
    else:
        form = SignUpForm()
    return render(request, 'gifts/signup.html', {'form': form})



class MemberListView(View):
    def get(self, request):
        ml = Member.objects.all()
        ctx = {'member_list': ml}
        return render(request, 'gifts/member_list.html', ctx)


class MemberCreate(OwnerCreateView):
    model = Member
    fields = '__all__'
    success_url = reverse_lazy('gifts:all')

class MemberUpdate(OwnerUpdateView):
    model = Member
    fields = '__all__'
    success_url = reverse_lazy('gifts:all')


class MemberDelete(OwnerDeleteView):
    model = Member
    fields = '__all__'
    success_url = reverse_lazy('gifts:all')


class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        f = get_object_or_404(Gift, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, gift=f)
        comment.save()
        return redirect(reverse('gifts:gift_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "gifts/gift_comment_delete.html"

    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        gift = self.object.gift
        return reverse('gifts:gift_detail', args=[gift.id])

class GiftListView(OwnerListView):
    model = Gift
    # By convention:
    template_name = "gifts/gift_list.html"

    def get(self, request) :
        strval = request.GET.get("search", False)
        if strval:
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            gift_list = Gift.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            gift_list = Gift.objects.all()

        favorites = list()
        if request.user.is_authenticated:
            # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
            rows = request.user.favorite_gifts.values('id')
            # favorites = [2, 4, ...] using list comprehension
            favorites = [ row['id'] for row in rows ]

        # Augment the post_list
        for obj in gift_list:
            obj.natural_updated = naturaltime(obj.updated_at)


        ctx = {'gift_list' : gift_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)


class MemberGiftListView(OwnerListView):
    model = Member
    # By convention:
    template_name = "gifts/member_gift_list.html"

    def get(self, request,pk) :
        m = Member.objects.get(id=pk)
        strval = request.GET.get("search", False)
        if strval:
            query = Q(title__icontains=strval)
            query.add(Q(text__icontains=strval), Q.OR)
            gift_list = Gift.objects.filter(owner_id= pk).filter(query).select_related().order_by('-updated_at')[:10]
        else:
            gift_list = Gift.objects.filter(owner_id = pk)


        # Augment the post_list
        for obj in gift_list:
            obj.natural_updated = naturaltime(obj.updated_at)


        ctx = {'gift_list' : gift_list, 'search': strval, 'member':m}
        return render(request, self.template_name, ctx)




class GiftDetailView(OwnerDetailView):
    model = Gift
    template_name = "gifts/gift_detail.html"

    def get(self, request, pk) :
        x = Gift.objects.get(id=pk)
        comments = Comment.objects.filter(gift=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'gift' : x, 'comments': comments, 'comment_form': comment_form}
        return render(request, self.template_name, context)


class GiftCreateView(OwnerCreateView):
#    model = Gift
#    fields = ['title', 'price','text']
    template_name = 'gifts/gift_form.html'
    success_url = reverse_lazy('gifts:all')

    def get(self, request, pk=None):
        form = CreateForm()

        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        #form.save_m2m()    # Giftd this
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        #form.save_m2m()    # Giftd this
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Giftd owner to the model before saving

        gift = form.save(commit=False)
        gift.owner = Member.objects.get(user = self.request.user)
        gift.save()
        form.save_m2m()
        return redirect(self.success_url)

class GiftCreateFromLinkView(OwnerCreateView):
    template_name = 'gifts/gift_form_link.html'
    success_url = reverse_lazy('gifts:all')

    def get(self, request):

        res = request.session.get('linkgen','')
        res_title = request.session.get('bs_title', 'Enter a Title')
        res_text = request.session.get('bs_text', 'Enter a Description')
        res_price = request.session.get('bs_price',0)
        res_img = request.session.get('picture', None)

        data_dict = {'title': res_title, 'text': res_text, 'link': res, 'price':res_price, 'picture':res_img}
        form = CreateForm(initial= data_dict)
        ctx = {'form': form , 'linkgen': res}

        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        if 'linksubmit' in request.POST:

            link_add = request.POST.get('linkgen')

            req = requests.get(link_add)
            bs = BeautifulSoup(req.text, 'html.parser')

            bs_html_title = bs.find(id="vi-lkhdr-itmTitl")
            bs_title = bs_html_title.text

            bs_html_desc = bs.find(class_="topItmCndDscMsg")
            if bs_html_desc == None :
                bs_desc = bs_title
            else:
                bs_desc = bs_html_desc.text

            bs_html_price = bs.find(id="prcIsum")
            bs_price = bs_html_price.text[4:]

            bs_img = bs.find(id="icImg")
            bs_img_dat = base64.b64encode(requests.get(bs_img['src']).content)

            data_dict = {'title': bs_title, 'text': bs_desc, 'link': link_add, 'price':bs_price, 'picture':bs_img_dat}
            form = CreateForm(initial= data_dict)

            ctx ={'bs_title' : bs_title, 'bs_text' : bs_desc, 'bs_price' : bs_price, 'linkgen':link_add, 'form':form, 'picture':bs_img_dat }
            return render(request, self.template_name, ctx)

        elif 'savesubmit' in request.POST:
            form = CreateForm(request.POST, request.FILES or None)
            # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
            #form.save_m2m()    # Giftd this
            if not form.is_valid():
                ctx = {'form': form}
                return render(request, self.template_name, ctx)
            # Add owner to the model before saving
            gift = form.save(commit=False)
            gift.owner = Member.objects.get(user = self.request.user)
            gift.save()
            form.save_m2m()
            return redirect(self.success_url)





class GiftUpdateView(OwnerUpdateView):
#    model = Gift
#    fields = ['title', 'price','text']
    template_name = 'gifts/gift_form.html'
    success_url = reverse_lazy('gifts:all')

    def get(self, request, pk):
        gift = get_object_or_404(Gift, id=pk, owner= Member.objects.get(user = self.request.user))
        form = CreateForm(instance=gift)

        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        gift = get_object_or_404(Gift, id=pk, owner=Member.objects.get(user = self.request.user))
        form = CreateForm(request.POST, request.FILES or None, instance=gift)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        gift = form.save(commit=False)
        gift.save()
        form.save_m2m()

        return redirect(self.success_url)

class GiftDeleteView(OwnerDeleteView):
    model = Gift



def stream_file(request, pk):
    gift = get_object_or_404(Gift, id=pk)
    response = HttpResponse()
    response['Content-Type'] = gift.content_type
    response['Content-Length'] = len(gift.picture)
    response.write(gift.picture)
    return response


# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation

gifts/templates/gifts/family_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Family</h1>

<p>
{% if family_list %}
<ul>
  {% for family in family_list %}
    <li>
        <a href="{% url 'gifts:family_detail'  family.id %}">{{ family.name }}</a>
        {% if family.owner == user %}
        (<a href="{% url 'gifts:family_update' family.id %}">Edit</a> |
        <a href="{% url 'gifts:family_delete' family.id %}">Delete</a>)
        {% endif %}

        {% if user.is_authenticated %}
        <a href="{% url 'gifts:family_join' %}">Join this family</a> |
        {% endif %}


    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no familys in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'gifts:family_create' %}">Add a family</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'gifts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'gifts:all' %}">Login</a>
{% endif %}
</p>



<script>
function favPost(url, family_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+family_id).toggle();
        $("#favorite_star_"+family_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>


{% endblock %}

gifts/templates/gifts/gift_comment_delete.html
{% extends "base_bootstrap.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'gifts:gift_detail' comment.gift.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

gifts/templates/gifts/gift_confirm_delete.html
{% extends "base_menu.html" %}
{% block content %}
<h1>Delete Gift</h1>

<p>Are you sure you want to delete the gift: {{ gift }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

gifts/templates/gifts/gift_detail.html
{% extends "base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->
{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}
{% block content %}

{% if gift.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'gifts:gift_picture' gift.id %}">
</div>
{% endif %}

<span style="float: right;">
({{ gift.updated_at|naturaltime }})
{% if gift.owner == user %}
<a href="{% url 'gifts:gift_update' gift.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'gifts:gift_delete' gift.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<h1>{{ gift.title }}</h1>

<div class = "row">
    {% if gift.content_type %}
    <div class="col-md-6">
        <p> Link:</p>
        <a href= "{{ gift.link }}"> {{ gift.link|truncatechars:20}} </a>
        <p>{{ gift.price }}</p>
        <p>{{ gift.text }}</p>
    </div>
    <div class="col-md-6">
        <div class="row"><img src="{% url 'gifts:gift_picture' gift.id %}"
            onclick="document.getElementById('overlay').style.display = 'block';"></div>
        <div class="row"><p class="text-muted"> Click the image to enlarge.</p></div>
    </div>
    {% else %}
    <div class="col-md-12">
        <p> Link:</p>
        <a href= "{{ gift.link }}"> {{ gift.link|truncatechars:20}} </a>
        <p>{{ gift.price }}</p>
        <p>{{ gift.text }}</p>
    </div>

    {% endif %}


</div>

{% if gift.tags.all %}
<p>Tags:
  {% for tag in gift.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'gifts:gift_comment_create' gift.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All Gifts" onclick="window.location.href='{% url 'gifts:all' %}';return false;">
</form>
</p>
{% endif %}

{% for comment in comments %}
<p> {{ comment.text }}
({{ comment.updated_at|naturaltime }})
{% if user == comment.owner %}
<a href="{% url 'gifts:gift_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</p>
{% endfor %}


<p><a href="{% url 'gifts:all' %}">All gifts</a></p>
{% endblock %}

gifts/templates/gifts/gift_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'gifts:all' %}';return false;">
  </form>
</p>

<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

gifts/templates/gifts/gift_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>gifts</h1>

<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'gifts:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>


<p>
{% if gift_list %}
<ul>
  {% for gift in gift_list %}
    <li>
        <a href="{% url 'gifts:gift_detail'  gift.id %}">{{ gift.title }}</a>
        {% if gift.owner == user %}
        (<a href="{% url 'gifts:gift_update' gift.id %}">Edit</a> |
        <a href="{% url 'gifts:gift_delete' gift.id %}">Delete</a>)
        {% endif %}

        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'gifts:gift_unfavorite' gift.id %}', {{ gift.id }} );return false;"
            {% if gift.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{gift.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'gifts:gift_favorite' gift.id %}', {{ gift.id }} );return false;"
            {% if gift.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{gift.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}


    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no gifts in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'gifts:gift_create' %}">Add an gift</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'gifts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'gifts:all' %}">Login</a>
{% endif %}
</p>



<script>
function favPost(url, gift_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+gift_id).toggle();
        $("#favorite_star_"+gift_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>


{% endblock %}

gifts/templates/gifts/member_gift_list.html
{% extends "base_menu.html" %}
{% block content %}
{% if gift.content_type %}

<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'gifts:gift_picture' gift.id %}">
</div>
{% endif %}

<h1>{{member.name}}'s Gifts</h1>

<div>
{% if gift_list %}
    <div class="row row-cols-3 row-cols-md-2 g-4">
        {% for gift in gift_list %}
        <div class = "col">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                    <div class ="col-md-8">
                        <h5 class="card-title">{{ gift.title }}</h5>
                        <p class="card-text">{{gift.text}}</p>
                        {% if gift.link %} <a href="{{gift.link}}" target="_blank">Gift Link</a> {% endif %}
                    </div>

                    <div class = "col-md-4">
                        {% if gift.content_type %}
                        <img class= "card-img img-fluid" src="{% url 'gifts:gift_picture' gift.id %}"
                            onclick="document.getElementById('overlay').style.display = 'block';">
                        {% endif %}
                    </div>
                    </div>
                </div>
                <div class="card-footer">
                        <a class="btn btn-light" href="{% url 'gifts:gift_detail'  gift.id %}">More Info!</a>
                        {% if gift.owner == member %}
                        <a class="btn btn-light" href="{% url 'gifts:gift_update' gift.id %}">Edit</a>
                        <a class="btn btn-light" href="{% url 'gifts:gift_delete' gift.id %}">Delete</a>
                        {% endif %}
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
    <p>There are no gifts for {{member.name}} in the database.</p>
{% endif %}
</div>

<p>
{% if user.is_authenticated %}
<a href="{% url 'gifts:gift_create' %}">Add a gift</a> |
<a href="{% url 'gifts:gift_link_create' %}">Add a gift from a link</a> |
<a href="{% url 'logout' %}?next={% url 'gifts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'gifts:all' %}">Login</a>
{% endif %}
</p>

<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}
  >
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'gifts:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>

{% endblock %}

gifts/templates/gifts/member_list.html
{% extends "base_menu.html" %}
{% block content %}
<h1>People with a gift list:</h1>

{% if member_list %}
<ul class="list-unstyled">
  {% for member in member_list %}
    <div class='row' style='margin-top:10px;'>
        <div class='col-12'>
            <li>
                <span class="glyphicon glyphicon-gift"></span>
                <a href="{% url 'gifts:member_gift_list'  member.id %}"> {{ member.name }}'s Gift List</a>

            </li>
        </div>
    </div>
  {% endfor %}
</ul>
{% else %}
  <p>There are no members in the database.</p>
{% endif %}

<p>
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'gifts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'gifts:all' %}">Login</a>
{% endif %}
</p>



{% endblock %}